[package]
name = "onchainfc"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "Apache 2.0"
authors = ["Fahim Ahmed (ahmed.fahim0207@gmail.com)"]      

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
onchainfc = "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"

[dev-dependencies]


[dev-addresses]


